# Application name (Optional but good practice)
# spring.application.name=geo_calculation_engine
#server.port=8081

# SpringBoot Logs
logging.level.org.springframework.r2dbc=DEBUG
logging.level.DPG.geo_calculation_engine=DEBUG
spring.main.log-startup-info=true
spring.main.banner-mode=log
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.format_sql=true

#------#------#------ DB CONFIGURATION ------#------#------#

# Configuration DB (calculator_engine) - PRIMARY CONNECTION
spring.r2dbc.url=r2dbc:postgresql://calculator_engine:calculator_engine@calculator-engine-db:5432/calculator_engine?currentSchema=engine_configuration

# Additional DB (postgis_calculator) - SECONDARY CONNECTION
spring.r2dbc.additional-datasources.calc.url=rr2dbc:postgresql://postgis_calculator:postgis_calculator@postgis-calculator-db:5432/postgis_calculator

# Cors
cors.urls=http://localhost,http://localhost:5173

# Pool Configuration (Applies primarily to the default connection, configure pooling if needed)
# spring.r2dbc.pool.enabled=true
# spring.r2dbc.pool.initial-size=10
# spring.r2dbc.pool.max-size=50

# Configurações para Helthchecker
management.endpoints.web.exposure.include=health,metrics,info
management.endpoint.health.show-details=always
