# Application name (Optional but good practice)
# spring.application.name=geo_calculation_engine
#server.port=8081

# SpringBoot Logs
logging.level.org.springframework.r2dbc=DEBUG
logging.level.DPG.geo_calculation_engine=DEBUG
spring.main.log-startup-info=true
spring.main.banner-mode=log
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.format_sql=true

#------#------#------ DB CONFIGURATION ------#------#------#

# Configuration DB (calculator_engine) - PRIMARY CONNECTION
spring.r2dbc.url=${DB_URL:r2dbc:postgresql://calculator-engine-db:5432/calculator_engine?currentSchema=engine_configuration}
spring.r2dbc.username=${DB_USER:calculator_engine}
spring.r2dbc.password=${DB_PASSWORD:calculator_engine}

# Additional DB (postgis_calculator) - SECONDARY CONNECTION
spring.r2dbc.additional-datasources.calc.url=${DB_CALC_URL:r2dbc:postgresql://postgis-calculator-db:5432/postgis_calculator}
spring.r2dbc.additional-datasources.calc.username=${DB_CALC_USER:postgis_calculator}
spring.r2dbc.additional-datasources.calc.password=${DB_CALC_PASSWORD:postgis_calculator}

# Cors
cors.urls=${CORS_URLS:http://localhost,http://localhost:5173}

# Pool Configuration (Applies primarily to the default connection, configure pooling if needed)
# spring.r2dbc.pool.enabled=true
# spring.r2dbc.pool.initial-size=10
# spring.r2dbc.pool.max-size=50

# Healthcheck endpoints
management.endpoints.web.exposure.include=health,metrics,info
management.endpoint.health.show-details=always
